name: vHive cri tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  cri-tests:
    name: CRI tests
    runs-on: [self-hosted, cri]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup environment
      run: ./scripts/setup_containerd.sh && export TMPDIR=~/tmp/

    - name: Build
      run: go build -race -v -a ./...

    - name: Run vHive end-to-end tests
      run: make test-cri
