name: vHive cri tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  cri-tests:
    name: CRI tests
    runs-on: [self-hosted, cri]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup environment
      run: ./scripts/setup_containerd.sh

    - name: Build
      env:
          GOCACHE: /root/tmp/gocache
          GOPATH: /root/tmp/go
      run: go build

    - name: Run vHive end-to-end tests
      env:
          GOCACHE: /root/tmp/gocache
          TMPDIR: /root/tmp/
      run: make test-cri
